import Navbar from "@/components/composition/navbar";
import "./globals.css";
import Footer from "@/components/composition/footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="pt-[56px]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
