import Navbar from "@/components/composition/navbar";
import "./globals.css";
import Footer from "@/components/composition/footer";
// import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata = {
  title: "rzrblade - Dev Super Toolbox",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
          <TooltipProvider>
            <Toaster position="top-center" />
            <Navbar />
            <div className="py-[53px] max-w-[var(--max-page-width)] mx-auto">
              {children}
            </div>
            <Footer />
          </TooltipProvider>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
