export const metadata = {
  title: "URL Builder - Composer | rzrblade",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  );
}
